### ISSUE TITLE
Consider OSS ordering

### ISSUE THREAD

**Issue by iamvery** [tech256/tech256.github.io#11]
How are the projects on http://tech256.com/community.html currently ordered? Any rhyme or reason? Maybe we should :abc:?

**Comment by blmeadows** [comment]
I added them in the order they were listed in #random. I can switch it to :abc:

**Comment by iamvery** [comment]
Awe, I intentionally didn't @mention you so that you wouldn't feel pressed to do this immediately. Don't sweat it if you're busy!

**Comment by blmeadows** [comment]
Ha, no pressure! I have to turn in a take home test this afternoon, and then it's Spring Break for me. :tada: I am SO happy to be doing this and not school work (Java :-1:) for a little while.

**Comment by iamvery** [comment]
haha yay! thanks so much for you help :dancers:

**Comment by blmeadows** [comment]
#14 Alphabetic order! :smiley:
