### ISSUE TITLE
Community page layout

### ISSUE THREAD

**Issue by iamvery** [tech256/tech256.github.io#12]
Currently we're using the big, floaty boxes. It's a little bulky IMO. Maybe we can clean it up into a nice list at some point?

**Comment by blmeadows** [comment]
Right now, when either of the pages are shrunk to about half screen the boxes are stacked on top of one another. Would that work better for the community page? They're still pretty big, though.
![screen shot 2016-03-17 at 11 19 27 am](https://cloud.githubusercontent.com/assets/9996491/13852862/2f009c88-ec32-11e5-8fda-e2b72b35bc6d.png)

**Comment by iamvery** [comment]
I was thinking of more a list. Smaller all around. It may be tough, because there aren't styles defined in this template to support anything like that.

**Comment by blmeadows** [comment]
Can you find an example of what you're thinking? And I'll see if I can make it work.

I can definitely do this but not sure if it's too boring now.
![screen shot 2016-03-17 at 11 34 34 am](https://cloud.githubusercontent.com/assets/9996491/13853348/540c49b2-ec34-11e5-9088-2300865899c4.png)

**Comment by iamvery** [comment]
Off the top of my head, idk of a good example, but here's a quick mockup of what I'm thinking. Might need to trim text down in some way or hide it behind a disclosure.

![example](https://cloud.githubusercontent.com/assets/79619/13853563/3feff6ee-ec35-11e5-97fd-5805339949b9.jpg)

**Comment by iamvery** [comment]
Just saw your screenshot! That's pretty legit, though the logos are a nice touch. Any way to easily include them?

**Comment by blmeadows** [comment]
#14 List ordering and the grey boxes just went away.
