### ISSUE TITLE
Add link to tech256.slack.com on tech256.com ??

### ISSUE THREAD

**Issue by mikebotts** [tech256/tech256.github.io#21]
We have a link on the Tech256.com site to join Slack256, but it would be helpful to also have a link to remind old people how to get to the tech256.slack.com if you've already joined?  

I know I can save a bookmark; I know there's a pattern for slack.com but its different from github; I know I'm getting old enough where I just don't want to think that hard; I also know I could just make the change myself but I wanted to check and see if you agree.  Otherwise, ignore this issue.

**Comment by iamvery** [comment]
That's a great idea! Would be valuable to add. I was also thinking about moving the "join" section up as well. Perhaps it's the most relevant part of the page. Shouldn't be buried at the bottom
